import {
  Applicant,
  ApplicantId,
  type Email,
  type FirstName,
  type LastName,
  type NetWorth,
  type Phone,
} from "@effect-redacted/shared/domain/Applicant"
import { Context, Effect, Layer, Redacted, Schema } from "effect"
import { SqlModel } from "effect/unstable/sql"
import type { SqlError } from "effect/unstable/sql/SqlError"

/**
 * Insert shape for an applicant. `netWorth` arrives wrapped in `Redacted`;
 * everywhere else in the codebase it stays wrapped. The unwrap happens at
 * exactly one place — inside `ApplicantRepoLive.insert` below.
 */
export type ApplicantInsert = {
  readonly firstName: FirstName
  readonly lastName: LastName
  readonly email: Email
  readonly phone: Phone
  readonly netWorth: Redacted.Redacted<NetWorth>
}

export class ApplicantRepo extends Context.Service<
  ApplicantRepo,
  {
    readonly insert: (
      input: ApplicantInsert,
    ) => Effect.Effect<ApplicantId, SqlError | Schema.SchemaError>
  }
>()("@db/ApplicantRepo") {}

/**
 * Live repository for `Applicant`.
 *
 * The CRUD machinery is generated by `SqlModel.makeRepository(Applicant, …)`:
 * `insert` runs `INSERT … RETURNING *` against Postgres and decodes the
 * result row through the Model.
 *
 * This wrapper exists for one reason: to confine `Redacted.value(…)` to a
 * single call site. The wrapped `netWorth` is unwrapped right before the
 * insert payload is handed to the generated repo. Grep `Redacted.value`
 * to audit — the ONE hit in src/ is the line below.
 */
export const ApplicantRepoLive = Layer.effect(
  ApplicantRepo,
  Effect.gen(function* () {
    const repo = yield* SqlModel.makeRepository(Applicant, {
      tableName: "applicants",
      spanPrefix: "Applicant",
      idColumn: "id",
    })
    return ApplicantRepo.of({
      insert: (input) =>
        Effect.gen(function* () {
          const id = yield* Schema.decodeUnknownEffect(ApplicantId)(crypto.randomUUID())
          const row = yield* repo.insert({
            id,
            firstName: input.firstName,
            lastName: input.lastName,
            email: input.email,
            phone: input.phone,
            netWorth: Redacted.value(input.netWorth),
          })
          return row.id
        }),
    })
  }),
)
